"""Digest schedule model for automated digest generation."""
from datetime import datetime
from typing import Optional, List
from sqlalchemy import String, Text, Integer, DateTime, Boolean, JSON, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class DigestSchedule(Base):
    """Schedule configuration for automated digest generation.

    Supports cron-based scheduling (e.g., "0 6 * * *" for 6 AM daily)
    with configurable lookback period, item limits, and AI settings.
    """
    __tablename__ = "digest_schedules"

    id: Mapped[int] = mapped_column(primary_key=True)

    # Domain association
    domain_id: Mapped[str] = mapped_column(String(50), nullable=False, index=True)

    # Schedule identity
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Cron schedule
    cron_expression: Mapped[str] = mapped_column(String(100), nullable=False)  # "0 6 * * *" = 6 AM daily
    timezone: Mapped[str] = mapped_column(String(50), default="UTC")
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)

    # Generation settings
    lookback_hours: Mapped[int] = mapped_column(Integer, default=24)  # Hours of content to include
    max_items: Mapped[int] = mapped_column(Integer, default=10)  # Max items per digest
    top_picks_count: Mapped[int] = mapped_column(Integer, default=3)  # "Top 3" highlight
    cluster_topics: Mapped[bool] = mapped_column(Boolean, default=True)  # Group by topic

    # Filter settings
    min_triage_score: Mapped[Optional[float]] = mapped_column(default=0.3, nullable=True)  # Min quality to include
    only_passed_triage: Mapped[bool] = mapped_column(Boolean, default=True)  # Only include passed items

    # AI settings
    ai_provider: Mapped[str] = mapped_column(String(50), default="gemini")
    ai_model: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # Auto-distribution (future feature)
    auto_email: Mapped[bool] = mapped_column(Boolean, default=False)
    email_recipients: Mapped[Optional[List[str]]] = mapped_column(JSON, nullable=True)

    # Tracking
    last_run_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    next_run_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    run_count: Mapped[int] = mapped_column(Integer, default=0)
    last_error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True, onupdate=datetime.utcnow)

    # Relationships
    generated_digests: Mapped[List["ScheduledDigest"]] = relationship(
        back_populates="schedule",
        cascade="all, delete-orphan"
    )

    def __repr__(self):
        return f"<DigestSchedule(id={self.id}, name='{self.name}', cron='{self.cron_expression}')>"


class ScheduledDigest(Base):
    """Record of a digest generated by a schedule.

    Links the schedule to the actual digest created, for history tracking.
    """
    __tablename__ = "scheduled_digests"

    id: Mapped[int] = mapped_column(primary_key=True)

    # Parent schedule
    schedule_id: Mapped[int] = mapped_column(ForeignKey("digest_schedules.id", ondelete="CASCADE"))
    schedule: Mapped["DigestSchedule"] = relationship(back_populates="generated_digests")

    # Generated digest
    digest_id: Mapped[int] = mapped_column(ForeignKey("digests.id", ondelete="CASCADE"))
    digest: Mapped["Digest"] = relationship()

    # Generation stats
    papers_considered: Mapped[int] = mapped_column(Integer, default=0)
    papers_included: Mapped[int] = mapped_column(Integer, default=0)
    topics_clustered: Mapped[int] = mapped_column(Integer, default=0)

    # Timing
    triggered_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    generation_time_seconds: Mapped[Optional[float]] = mapped_column(nullable=True)

    def __repr__(self):
        return f"<ScheduledDigest(schedule_id={self.schedule_id}, digest_id={self.digest_id})>"


# Import here to avoid circular import
from app.models.digest import Digest
