"""Markdown newsletter composer."""
from app.models.digest import Digest


class MarkdownComposer:
    """Compose Markdown newsletters from digests."""
    
    async def compose(self, digest: Digest) -> str:
        """Compose a Markdown newsletter."""
        
        lines = []
        
        # Header
        lines.append(f"# {digest.name}")
        lines.append("")
        lines.append("*Science Digest Newsletter*")
        lines.append("")
        lines.append("---")
        lines.append("")
        
        # Intro
        if digest.intro_text:
            lines.append(digest.intro_text)
            lines.append("")
            lines.append("---")
            lines.append("")
        
        # Papers
        for i, dp in enumerate(digest.digest_papers, 1):
            paper = dp.paper
            
            # Headline
            headline = paper.summary_headline or paper.title
            lines.append(f"## {i}. {headline}")
            lines.append("")
            
            # Meta
            meta_parts = []
            if paper.journal:
                meta_parts.append(f"**Journal:** {paper.journal}")
            if paper.authors:
                authors = ", ".join(a.name for a in paper.authors[:3])
                meta_parts.append(f"**Authors:** {authors}")
            if paper.is_preprint:
                meta_parts.append("⚠️ *Preprint*")
            
            if meta_parts:
                lines.append(" | ".join(meta_parts))
                lines.append("")
            
            # Image
            if paper.image_path:
                lines.append(f"![{headline}]({paper.image_path})")
                lines.append("")
            
            # Takeaway
            if paper.summary_takeaway:
                lines.append(paper.summary_takeaway)
                lines.append("")
            
            # Why it matters
            if paper.summary_why_matters:
                lines.append(f"> {paper.summary_why_matters}")
                lines.append("")
            
            # Credibility
            if paper.credibility_score is not None:
                score = round(paper.credibility_score)
                if score >= 70:
                    emoji = "🟢"
                elif score >= 50:
                    emoji = "🟡"
                else:
                    emoji = "🔴"
                
                lines.append(f"**Credibility Score:** {emoji} {score}/100")
                if paper.credibility_note:
                    lines.append(f"*{paper.credibility_note}*")
                lines.append("")
            
            # Tags
            if paper.tags:
                tags_str = " ".join(f"`{tag}`" for tag in paper.tags)
                lines.append(f"**Tags:** {tags_str}")
                lines.append("")
            
            # Link
            if paper.url:
                lines.append(f"[Read full paper →]({paper.url})")
                lines.append("")
            
            lines.append("---")
            lines.append("")
        
        # Conclusion
        if digest.conclusion_text:
            lines.append(digest.conclusion_text)
            lines.append("")
        
        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by Science Digest*")
        
        return "\n".join(lines)
